# Generated by Django 2.1.2 on 2018-11-02 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(null=True, on_delete=True, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Takip edililen kullanıcı')),
                ('follower', models.ForeignKey(null=True, on_delete=True, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Takip eden kullanıcı')),
            ],
        ),
    ]
