# Generated by Django 2.0.6 on 2019-02-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='following',
            options={'verbose_name_plural': 'Takipleşme Sistemi'},
        ),
    ]
