# Generated by Django 2.1.2 on 2018-10-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181012_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=10, verbose_name='Kategori İsmi')),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
    ]
