# Generated by Django 2.1.2 on 2018-10-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181013_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/marijuana.jpg', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to='blog', verbose_name='Resim'),
        ),
    ]
