# Generated by Django 2.0.6 on 2019-02-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20181102_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='kategoriler',
            field=models.ManyToManyField(null=True, related_name='blog', to='blog.Kategori'),
        ),
    ]
