# Generated by Django 2.1.2 on 2018-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Başlık bilgisi burada girilir.', max_length=100, null=True, verbose_name='Başlık ')),
                ('content', models.TextField(max_length=1000, null=True, verbose_name='İçerik')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
