# Generated by Django 2.1.2 on 2018-10-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='kategoriler',
            field=models.ManyToManyField(related_name='blog', to='blog.Kategori'),
        ),
    ]
