# Generated by Django 2.1.2 on 2018-10-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181013_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='default/marijuana', help_text='Kapak Fotoğrafı Yükleyiniz', null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
