# Generated by Django 2.1.2 on 2018-10-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comment_comment_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Yorumlar'},
        ),
    ]
