# Generated by Django 2.1.2 on 2018-10-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181020_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=True, related_name='comment', to='blog.Blog'),
        ),
    ]
