# Generated by Django 2.1.2 on 2018-11-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_favoriteblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteblog',
            options={'verbose_name_plural': 'Favorilere Eklenen Gönderileri'},
        ),
    ]
