# Generated by Django 2.2.5 on 2019-09-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_counties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counties',
        ),
    ]
