# Generated by Django 2.2.5 on 2019-09-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_countie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countie',
            options={'verbose_name_plural': 'Counties'},
        ),
    ]
