# Generated by Django 2.2.5 on 2019-09-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20190913_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidences',
            name='counties',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
