# Generated by Django 2.2.5 on 2019-09-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_incidences_counties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='counties',
            field=models.CharField(default='Erzurum', max_length=25, null=True),
        ),
    ]
